[profile.default]
src = "contracts/src"
script = "contracts/script"
test = "contracts/test"
out = "contracts/out"
libs = ["lib"]

solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

remappings = [
  "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
  "@chainlink/contracts/=node_modules/@chainlink/contracts/",
  "@openzeppelin/contracts@5.0.2/=node_modules/@openzeppelin/contracts/",
  "@openzeppelin/=node_modules/@openzeppelin/"
]
